export const ADD_TO_MYLIST = "COMMAND/ADD_TO_MYLIST";
export const REMOVE_FROM_MYLIST = "COMMAND/REMOVE_FROM_MYLIST";
export const ADD_TO_RECOMMENDATIONS = "COMMAND/ADD_TO_RECOMMENDATIONs";
export const REMOVE_FROM_RECOMMENDATIONS = "COMMAND/REMOVE_FROM_RECOMMENDATION";
export const FETCH_DATA='COMMAND/FETCH_DATA';
export const REQUEST_SUCCEEDED='API/REQUEST_SUCCEEDED'
